### ISSUE TITLE
关于data.json文件的问题

### ISSUE THREAD

**Issue by george513** [AirtestProject/multi-device-runner#1]
您好 作者，请问下load_jdon_data方法里的data.json 文件内容是怎么生成的，需要在编写脚本的时候自己写代码实现，生成data.json？

**Comment by EraChen233** [comment]
data.json 是用来记录运行进度的，不需要自己编写
在有这个文件的情况下，脚本会读取这个文件继续上一次的进度继续运行
删除这个文件，airtest测试会重新在多个设备上运行

**Comment by george513** [comment]
现在这个run.py执行，是不是不支持批量.air运行？如果支持，怎么使用？

**Comment by EraChen233** [comment]
这个项目只是作为参考，可以实现单个air文件在多个设备上并行运行。
如果需要执行多个air文件，可以修改这个项目的 run.py 代码
或者了解一下我们的airlab项目，目前正在免费试用中 https://airlab.163.com/

**Comment by loneyao** [comment]
很奇怪，我都配置了为python3，但是还是python2.7的去跑，我自己的都是python3去运行的。

[03:22:58][DEBUG]<airtest.core.android.adb> /usr/local/lib/python2.7/site-packages/airtest/core/android/static/adb/mac/adb -s JJRNW17125008266 wait-for-device
[03:22:58][DEBUG]<airtest.core.android.adb> /usr/local/lib/python2.7/site-packages/airtest/core/android/static/adb/mac/adb -s af1e4da wait-for-device
[03:22:58][DEBUG]<airtest.core.android.adb> /usr/local/lib/python2.7/site-packages/airtest/core/android/static/adb/mac/adb -s af1e4da shell getprop ro.build.version.sdk
[03:22:58][DEBUG]<airtest.core.android.adb> /usr/local/lib/python2.7/site-packages/airtest/core/android/static/adb/mac/adb -s JJRNW17125008266 shell getprop ro.build.version.sdk
[03:22:58][DEBUG]<airtest.core.android.adb> /usr/local/lib/python2.7/site-packages/airtest/core/android/static/adb/mac/adb -s JJRNW17125008266 shell pm list packages

**Comment by loneyao** [comment]
而且跑完后的，报告是没有内容的。

**Comment by CrazySnail1** [comment]
> 很奇怪，我都配置了为python3，但是还是python2.7的去跑，我自己的都是python3去运行的。
> 
> [03:22:58][DEBUG]<airtest.core.android.adb> /usr/local/lib/python2.7/site-packages/airtest/core/android/static/adb/mac/adb -s JJRNW17125008266 wait-for-device
> [03:22:58][DEBUG]<airtest.core.android.adb> /usr/local/lib/python2.7/site-packages/airtest/core/android/static/adb/mac/adb -s af1e4da wait-for-device
> [03:22:58][DEBUG]<airtest.core.android.adb> /usr/local/lib/python2.7/site-packages/airtest/core/android/static/adb/mac/adb -s af1e4da shell getprop ro.build.version.sdk
> [03:22:58][DEBUG]<airtest.core.android.adb> /usr/local/lib/python2.7/site-packages/airtest/core/android/static/adb/mac/adb -s JJRNW17125008266 shell getprop ro.build.version.sdk
> [03:22:58][DEBUG]<airtest.core.android.adb> /usr/local/lib/python2.7/site-packages/airtest/core/android/static/adb/mac/adb -s JJRNW17125008266 shell pm list packages

你是用python的ide跑的吧 ，需要自己指定下使用的python版本。在命令行里直接用python3 run.py 就不会存在这个问题

**Comment by 2454760302hui** [comment]
谢谢 ，本地测试已通过，请教个小问题，想把生成的报告，通过邮件发送，但是生成报告的log目录，查看html，是找不到本地图片的，该如何把浏览器生成的报告 通过邮件发送呢？

**Comment by yimelia** [comment]
@2454760302hui 
可以参考文档的这里：https://airtest.doc.io.netease.com/IDEdocs/about_report/Report_guidelines/#_10
生成报告时添加`--export`来导出报告，这样就会包含静态文件+图片了，然后再把整个文件夹打包发给别人

**Comment by 2454760302hui** [comment]
好的 ，谢谢，try~

**Comment by 2454760302hui** [comment]
你好，根据你的提示，目前已完成，有些麻烦，因为目前采用的是unitest 执行airtest脚本，报告采用的是beautiful report ，但是没有截图作为辅助，有些突兀，所以想在unitest中，如何把airtest的报告增加到其中，目前先暂时采用yagmail 添加附件的方式发送，也能达到预期效果，如何在当前的代码结构中生成，或者其他的办法？？

**Comment by yimelia** [comment]
可以直接翻airtest/report/report.py里的源码然后在你们的代码里调用对应的接口，但是report.py最近正在做修改，最新版本可能要查看这里： https://github.com/AirtestProject/Airtest/pull/618

`report_data`这个接口会获取到当前报告里的所有信息（[源码位置](https://github.com/AirtestProject/Airtest/pull/618/files#diff-34f21f9a38652562fd568c4b93f180feR418)），然后如果你们有自己的报告模板的话，可以直接拿了这个数据自己去生成

**Comment by 2454760302hui** [comment]
ok，try  thanks

**Comment by 2454760302hui** [comment]
@yimelia 使用unittest 执行airtest脚本，识别poco的适合 ，貌似 识别
步骤：
1.连接上两个设备
2.单个设备脚本调试，并确定通过
3.使用unittest执行所以脚本，到poco识别的地方，不能识别元素导致失败，但是单独调试却是通过的，什么原因呢，请指教~
start = time.time()
        while not self.exists():
            self.poco.sleep_for_polling_interval()
            if time.time() - start > timeout:
>               raise PocoTargetTimeout('appearance', self)
E               poco.exceptions.PocoTargetTimeout: Waiting timeout for appearance of "UIObjectProxy of
