### ISSUE TITLE
Subprocess.Popen(cmd,cwd=os.getcwd())这个命令执行的时候脚本其实就运行了，本质还是顺序执行的，没达到真正的并行呢

### ISSUE THREAD

**Issue by lxf920125** [AirtestProject/multi-device-runner#3]

**Comment by EraChen233** [comment]
这个sample说的并行，是指设备间并行，并不是脚本并行，具体可看这个示意图
sample只是作为参考，如需更多功能，请自行实现
![image](https://github.com/AirtestProject/multi-device-runner/raw/master/docs/demonstrate.png)
