### ISSUE TITLE
terminal 中运行Run脚本报ModuleNotFoundError: No module named 'xxxx'.

### ISSUE THREAD

**Issue by 447098173** [AirtestProject/multi-device-runner#4]

**Comment by yimelia** [comment]
建议先百度这个报错是什么含义，然后在本地安装好python环境和对应缺失的库

**Comment by 447098173** [comment]
ERROR: runTest (airtest.cli.runner.AirtestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\python\lib\site-packages\airtest\cli\runner.py", line 66, in runTest
    six.reraise(*sys.exc_info())
  File "c:\python\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "c:\python\lib\site-packages\airtest\cli\runner.py", line 62, in runTest
    exec(compile(code.encode("utf-8"), pyfilepath, 'exec'), self.scope)
  File "C:\Users\ext.chen.chen\mobile\SSPT\Test\Android\CN.air\CN.py", line 6, in <module>
    from SSPT.Test.Android.Base import Base
ModuleNotFoundError: No module named 'SSPT'

----------------------------------------------------------------------
Ran 1 test in 0.253s

这是报错的log，报错缺失的不是某个python的库。.air文件夹也在SSPT.Test.Android路径下，在pycharm里面run是可以成功的，但是发现它会默认Working directory在\SSPT\Test\Android。

**Comment by yimelia** [comment]
所以在sys.path中添加SSPT的父路径，让搜索目录能够找得到SSPT就可以了

**Comment by 447098173** [comment]
─ my-testflow/
   --- SSPT
       ----Test
            -----Android
                  ------CN.air
                          ------CN.py   （from Base import Base）
                  -------run.py
                  -------Base.py

在CN.py里面添加了sys.path.append('SSPT父路径')，terminal里面run run.py依然还是报No module named“SSPT”.

**Comment by yimelia** [comment]
@447098173 
这种搜索路径找不到的问题，需要本地调试，我无法通过描述来判断具体的情况。因为没有具体代码，也没有具体的环境，无法手把手帮你调试。

建议把sys.path路径print出来看看是否包含了SSPT所在的父目录（即my-testflow的目录**绝对路径**），并且请在import SSPT的那行代码运行**之前**，确保环境中能够查找到SSPT所在的父路径。

这个问题是python相关的问题，与本项目无关，建议尽量自行调试
