### ISSUE TITLE
没有log.html

### ISSUE THREAD

**Issue by CrazySnail1** [AirtestProject/multi-device-runner#7]
![image](https://user-images.githubusercontent.com/13583767/62592960-b1c68d80-b907-11e9-958c-3bc94c9debb0.png)

为啥我的每个手机的测试报告只有log.txt, 没有对应的html，是airtest report生成报告的脚本失效了吗？还是我打开的方式不对？report.html里边的产看详情也是没有此文件。

**Comment by EraChen233** [comment]
运行的时候会有很多输出，看一下错误信息

**Comment by CrazySnail1** [comment]
这个是跑完单机测试的日志截图，中间没有异常中断，其他手机也是这样

![image](https://user-images.githubusercontent.com/13583767/62598608-826e4b80-b91c-11e9-958d-4ddcdb0b1f2f.png)

**Comment by EraChen233** [comment]
有这个输出，表示你的airtest命令行错误了，所以出现了提示。在run,py中输出你的cmd命令，参照这个文档自行检查吧
http://airtest.netease.com/docs/cn/4_run_script/run_script.html#id7

![image](https://user-images.githubusercontent.com/5961185/62603189-f530f400-b927-11e9-8502-12d08d3ac13d.png)

**Comment by CrazySnail1** [comment]
> 有这个输出，表示你的airtest命令行错误了，所以出现了提示。在run,py中输出你的cmd命令，参照这个文档自行检查吧
> http://airtest.netease.com/docs/cn/4_run_script/run_script.html#id7
> 
> ![image](https://user-images.githubusercontent.com/5961185/62603189-f530f400-b927-11e9-8502-12d08d3ac13d.png)

脚本里答应出来是这个：
![image](https://user-images.githubusercontent.com/13583767/62614346-ce7db800-b93d-11e9-9c77-63ce4489df57.png)



我把命令输出后，在我的中端可以执行的：
![image](https://user-images.githubusercontent.com/13583767/62613911-fcaec800-b93c-11e9-833c-6ae0020364ef.png)



----------------------------------解决方案----------------------------------------
将第二个参数改为False，就可以了！
  ret = subprocess.call(cmd, shell=False, cwd=os.getcwd())
